### ISSUE TITLE
JS Lint your code!

### ISSUE THREAD

**Issue by phlco** [NathanRiemer/concentration#1]
Hiya! I just ran your code through http://www.jshint.com

It can give you some helpful warnings about things to correct

Here's the output with the line numbers and problems.  See if any of these help!

```
One warning
227 Missing semicolon.
```

**Comment by NathanRiemer** [comment]
Thanks Phil! I actually had already run my code through JSHint a couple hours ago and caught that missing semi-colon but hadn't committed yet (was taking a break from coding). 
I'd ask if you had a chance to look over my code and if so, had any thoughts, but I'm guessing you automated this issue for everyone.

**Comment by phlco** [comment]
<3
